[package]
name = "mantis"
version = "0.1.0"
edition = "2021"

[lib]
name = "mantis"
path = "src/lib.rs"

[dependencies]
ndarray = "0.15.6"
num-traits = "0.2.17"
uuid = { version = "1.7.0", features = ["v4"] }